### ISSUE TITLE
facing error while runnnig the project 

### ISSUE THREAD

**Issue by Sibints2000** [AI2Enginex/Brain-Tumor-Classification#2]
![Screenshot 2023-03-21 201326](https://user-images.githubusercontent.com/62069255/226642339-8ba9cc28-56bf-4ff9-b24c-950a2da3bc83.png)

can u fix this error

**Comment by AI2Enginex** [comment]
please share the pic of entire code

**Comment by AI2Enginex** [comment]
> ![Screenshot 2023-03-21 201326](https://user-images.githubusercontent.com/62069255/226642339-8ba9cc28-56bf-4ff9-b24c-950a2da3bc83.png)
> 
> can u fix this error

I have updated the file please check , also you need to perform data augmentation for generating new images for testing set to avoid overfitting

**Comment by Sibints2000** [comment]
thank u
