### ISSUE TITLE
facing error in tumor_app.py

### ISSUE THREAD

**Issue by Sibints2000** [AI2Enginex/Brain-Tumor-Classification#3]
![Screenshot 2023-03-22 130817](https://user-images.githubusercontent.com/62069255/226832816-7d67fbf9-c6ba-4d2f-82bc-66526c2f1202.png)

looks like the attribute is outdated

**Comment by AI2Enginex** [comment]
> ![Screenshot 2023-03-22 130817](https://user-images.githubusercontent.com/62069255/226832816-7d67fbf9-c6ba-4d2f-82bc-66526c2f1202.png)
> 
> 
> looks like the attribute is outdated 

please share your code 

the correct syntax is 

from keras.preprocessing import image

**Comment by Sibints2000** [comment]
![Screenshot 2023-03-22 151032](https://user-images.githubusercontent.com/62069255/226863262-e4f62d61-694c-4ae9-8a67-e7ad371121de.png)
![Screenshot 2023-03-22 151050](https://user-images.githubusercontent.com/62069255/226863261-f9c2ad43-ab6c-42d8-9dd7-a0cf6c066e9c.png)
![Screenshot 2023-03-22 151107](https://user-images.githubusercontent.com/62069255/226863307-abaa62a7-c791-4cbd-90b2-35c79429eb18.png)

**Comment by Sibints2000** [comment]
is it because of python version??

**Comment by AI2Enginex** [comment]
from keras.preprocessimg import image

image.img_to_arr

please try this

**Comment by Sibints2000** [comment]
![Screenshot 2023-03-22 175400](https://user-images.githubusercontent.com/62069255/226904176-b37e1326-484b-4e08-aacc-4bae57580a4a.png)

same issue bro

**Comment by Sibints2000** [comment]
![Screenshot 2023-03-22 181148](https://user-images.githubusercontent.com/62069255/226907855-163c5079-0277-4374-9241-2b5c2cf6533f.png)


is it because of this warning

could u also help me with augmentation

**Comment by AI2Enginex** [comment]
no you are writing it wrong

instead of writing :

from keras.preprocessing.image import image

try writing :

from keras.preprocessing import image
